export default Object.freeze({
  types: {
    service: ['administration', 'bank', 'book', 'cemetery', 'firefighter', 'mail', 'music', 'police', 'school'],
    care: ['animal', 'defibrillator', 'dental', 'lab', 'medic', 'pharmacy'],
    catering: ['bar', 'cellar', 'restaurant', 'tobacco'],
    sport: ['basket', 'bocce', 'foot', 'pingpong', 'pool', 'rugby', 'skate', 'tennis'],
    shop: ['beauty', 'bakery', 'butcher', 'diy', 'fish', 'garden', 'grocery'],
    nature: ['park', 'recycle'],
    transport: ['bus', 'car', 'gas', 'train'],
    tourism: ['castle', 'church', 'landmark', 'museum', 'tourism']
  },
  subtypes: {
    restaurant: new window.L.Icon({
      iconUrl: 'assets/images/marker/restaurant.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    bar: new window.L.Icon({
      iconUrl: 'assets/images/marker/bar.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    cellar: new window.L.Icon({
      iconUrl: 'assets/images/marker/cellar.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    tobacco: new window.L.Icon({
      iconUrl: 'assets/images/marker/tobacco.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    grocery: new window.L.Icon({
      iconUrl: 'assets/images/marker/grocery.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    diy: new window.L.Icon({
      iconUrl: 'assets/images/marker/diy.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    beauty: new window.L.Icon({
      iconUrl: 'assets/images/marker/beauty.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    foot: new window.L.Icon({
      iconUrl: 'assets/images/marker/foot.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    rugby: new window.L.Icon({
      iconUrl: 'assets/images/marker/rugby.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    basket: new window.L.Icon({
      iconUrl: 'assets/images/marker/basket.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    pool: new window.L.Icon({
      iconUrl: 'assets/images/marker/pool.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    pingpong: new window.L.Icon({
      iconUrl: 'assets/images/marker/pingpong.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    skate: new window.L.Icon({
      iconUrl: 'assets/images/marker/skate.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    bocce: new window.L.Icon({
      iconUrl: 'assets/images/marker/bocce.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    tennis: new window.L.Icon({
      iconUrl: 'assets/images/marker/tennis.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    bakery: new window.L.Icon({
      iconUrl: 'assets/images/marker/bakery.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    fish: new window.L.Icon({
      iconUrl: 'assets/images/marker/fish.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    butcher: new window.L.Icon({
      iconUrl: 'assets/images/marker/butcher.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    book: new window.L.Icon({
      iconUrl: 'assets/images/marker/book.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    music: new window.L.Icon({
      iconUrl: 'assets/images/marker/music.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    landmark: new window.L.Icon({
      iconUrl: 'assets/images/marker/landmark.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    castle: new window.L.Icon({
      iconUrl: 'assets/images/marker/castle.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    church: new window.L.Icon({
      iconUrl: 'assets/images/marker/church.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    tourism: new window.L.Icon({
      iconUrl: 'assets/images/marker/tourism.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    museum: new window.L.Icon({
      iconUrl: 'assets/images/marker/museum.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    garden: new window.L.Icon({
      iconUrl: 'assets/images/marker/garden.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    car: new window.L.Icon({
      iconUrl: 'assets/images/marker/car.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    gas: new window.L.Icon({
      iconUrl: 'assets/images/marker/gas.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    train: new window.L.Icon({
      iconUrl: 'assets/images/marker/train.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    bus: new window.L.Icon({
      iconUrl: 'assets/images/marker/bus.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    animal: new window.L.Icon({
      iconUrl: 'assets/images/marker/animal.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    dental: new window.L.Icon({
      iconUrl: 'assets/images/marker/dental.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    pharmacy: new window.L.Icon({
      iconUrl: 'assets/images/marker/pharmacy.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    medic: new window.L.Icon({
      iconUrl: 'assets/images/marker/medic.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    lab: new window.L.Icon({
      iconUrl: 'assets/images/marker/lab.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    defibrillator: new window.L.Icon({
      iconUrl: 'assets/images/marker/defibrillator.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    cemetery: new window.L.Icon({
      iconUrl: 'assets/images/marker/cemetery.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    firefighter: new window.L.Icon({
      iconUrl: 'assets/images/marker/firefighter.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    police: new window.L.Icon({
      iconUrl: 'assets/images/marker/police.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    mail: new window.L.Icon({
      iconUrl: 'assets/images/marker/mail.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    bank: new window.L.Icon({
      iconUrl: 'assets/images/marker/bank.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    park: new window.L.Icon({
      iconUrl: 'assets/images/marker/park.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    recycle: new window.L.Icon({
      iconUrl: 'assets/images/marker/recycle.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    administration: new window.L.Icon({
      iconUrl: 'assets/images/marker/administration.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    school: new window.L.Icon({
      iconUrl: 'assets/images/marker/school.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20],
    }),
    user: new window.L.Icon({
      iconUrl: 'assets/images/marker/user.svg',
      iconSize: [26, 26],
      iconAnchor: [13, 13],
      popupAnchor: [0, -13],
      shadowUrl: 'assets/images/marker/marker-shadow.png',
      shadowSize: [42, 42],
      shadowAnchor: [20, 20]
    })
  }
});
